FROM python:3.12-slim AS builder

WORKDIR /interesting

COPY . /interesting

RUN pip install --upgrade pip
RUN pip install -r requirements.txt


EXPOSE 8000

CMD ["sh", "-c", "python main.py & python kafka.consumer.py"]
