FROM python:3.12

WORKDIR /app

COPY . /app/interesting

RUN pip install --upgrade pip
RUN pip install -r interesting/requirements.txt


EXPOSE 8000

CMD ["sh", "-c", "  python -m interesting.main & python -m interesting.kafka.consumer"]
