FROM python:3.12

WORKDIR /app

COPY . /app/not_interesting

RUN pip install --upgrade pip
RUN pip install -r not_interesting/requirements.txt


EXPOSE 8000

CMD ["sh", "-c", "  python -m not_interesting.main & python -m not_interesting.kafka.consumer"]
